spring.datasource.url=your-rul
spring.datasource.username=your-username
spring.datasource.password=your-pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
openrouter.api.key=you-api
openrouter.url=your-url

qdrant.url=your-url
qdrant.api.key=your-API

jina.api.key=your-api
jina.embedding.url=your-url


server.port=8080
